env:
  commonjs: true
  es6: true
  browser: true

extends: eslint:recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-unused-vars: [warn]
  no-empty: [warn]
  prefer-const: [warn]

  semi: [warn, never]
  quotes: [warn, single]
  comma-dangle: [warn, never]
  indent: [warn, 2, { SwitchCase: 1 }]
